version: '3.4'

services: 
    service1:
        image: service1
        build: 
            context: ./service1
            dockerfile: ./Dockerfile
        volumes: 
            - ./service1:/app
        ports: 
            - 5000:5000
    
    service2:
        image: service2
        build: 
            context: ./service2
            dockerfile: ./Dockerfile
        volumes: 
            - ./service2:/usr/src/app
        environment: 
            NODE_ENV: production
        ports: 
            - 3000:3000
        depends_on: 
            - service1

  
